# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CodingChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SwiftLint'

  # Pods for CodingChallenge

  target 'CodingChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CodingChallengeUITests' do
    # Pods for testing
  end

end
